sudo: require
language: cpp
compiler: gcc


addons: 
  apt: 
    packages: libboost-all-dev

before_install:

  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq librapidxml-dev libsdl2-mixer-dev libdevil-dev


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

script:
 - qmake
 - make
 - ./Mario
